/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 watch.gltf 
Author: ar-watches (https://sketchfab.com/ar-watches)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/patek-philippe-two-crown-worldtime-8dcbe0f77aba4a58ada60048387b12c8
Title: Patek Philippe Two-Crown Worldtime
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/watch.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.with_uv_Object003_watch_0.geometry} material={materials.watch} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
        <mesh geometry={nodes.Hand_1_watch_0.geometry} material={materials.watch} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
        <mesh geometry={nodes.Object001_watch_0.geometry} material={materials.watch} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
        <mesh geometry={nodes.Box001_glass_0.geometry} material={materials.glass} position={[0, 0, 42.926]} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
        <mesh geometry={nodes.Object002_watch_0.geometry} material={materials.watch} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
        <mesh geometry={nodes.Object003_watch_0.geometry} material={materials.watch} rotation={[-Math.PI / 2, 0, 0]} scale={2.54} />
      </group>
    </group>
  )
}

useGLTF.preload('/watch.gltf')
