/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 necklace.gltf 
Author: cedeon (https://sketchfab.com/cedeon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gothic-pendant-necklace-da1b584886b94a7fb9c98dd642a319b3
Title: Gothic Pendant Necklace
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/necklace/necklace.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.005}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.082, 40.892, -185.823]} rotation={[-Math.PI / 2, 0, 0]} scale={697.69}>
            <mesh geometry={nodes.chain1_M_Chrome_0.geometry} material={materials.M_Chrome} scale={0.788} />
            <mesh geometry={nodes.chain1001_M_Chrome_0.geometry} material={materials.M_Chrome} position={[-0.002, -0.237, -0.055]} rotation={[0, -Math.PI / 2, 0]} scale={1.048} />
          </group>
          <mesh geometry={nodes.PendantGothic_M_Pendant_LP_0.geometry} material={materials.M_Pendant_LP} rotation={[-1.62, -0.006, Math.PI / 2]} scale={[99.998, 99.999, 38.347]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/necklace/necklace.gltf')
