/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ring.gltf 
Author: Qifan Zhang (https://sketchfab.com/qifanzhang)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/an-old-ring-ea5e0c11f2e046c993239ea1a3efcad7
Title: An Old Ring
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/ring/ring.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.139, 0.06, -0.039]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.ring_low_EMP_Accessories_0.geometry} material={materials.EMP_Accessories} position={[-1.14, -20.23, -24.345]} rotation={[-1.589, 0.252, -0.783]} scale={5.983} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/ring/ring.gltf')
